### ISSUE TITLE
Can't seem to figure out how this works

### ISSUE THREAD

**Issue by Lorenps** [JayChen35/spotify-to-mp3-python#13]
In "Read me" you say: "When inputting this into the script, make sure to only input the characters after "spotify:playlist:". ", but I'm not sure where I have to input the URI or what to do with my Client ID or my Client Secret. 

Also if I run the script "python3 spotify_to_mp3.py" I get this: 
Traceback (most recent call last):
  File "/home/Lorenzo/spotify-to-mp3-python/spotify_to_mp3.py", line 7, in <module>
     import yt_dlp
ModuleNotFoundError: No module named ' yt_dlp '

![ ](https://user-images.githubusercontent.com/110701043/183224132-b8a82402-d428-40fa-aab3-8b611413f36c.png)

Also as you can tell I don't know much about python, but I'm trying to get into it.
If you could help that would be much appreciated and I appreciate a lot what you do!

**Comment by everettperiman** [comment]
It seems that you are missing some of the required libraries for the script to run correctly. Did you follow all of the steps on the README? 
https://github.com/JayChen35/spotify-to-mp3-python#2-installing-dependencies

**Comment by Lorenps** [comment]
I followed all of the steps, and I'm pretty sure I've got pip and I have ran "pip3 install spotipy && pip3 install youtube_dl && pip3 install youtube_search" with this output:

![1](https://user-images.githubusercontent.com/110701043/184964414-02e462df-8b3b-4d03-a0cc-f736186dec5c.png)

I have no idea what any of that means but I'm pretty sure It's telling me that everything is installed

**Comment by everettperiman** [comment]
Can you try to install the packages using " python3 -m pip install spotipy && python3 -m pip install youtube_dl && python3 -m pip install youtube_search "?

**Comment by Lorenps** [comment]
> Can you try to install the packages using " python3 -m pip install spotipy && python3 -m pip install youtube_dl && python3 -m pip install youtube_search "?

That didn't work, but later I tried again on another linux device and it worked. Thanks a lot.
