### ISSUE TITLE
Problem: Only valid bearer authentication supported

### ISSUE THREAD

**Issue by jscardin** [JayChen35/spotify-to-mp3-python#4]
Hello,

I cloned your code and tried it, thanks a lot by the way,

but I get this error:

HTTP Error for GET to https://api.spotify.com/v1/playlists/8acf5c4e7b0f4c64 returned 400 due to Only valid bearer authentication supported

Would you know by any chance what it means? I have premium account with Spotify, I created the app and input the client ID, secrets and username as requested.

**Comment by jscardin** [comment]
OK I fixed the problem, don't bother.

**Comment by JayChen35** [comment]
Glad you fixed your error! Sorry I wasn't able to help in time.
